import { createContext, useContext, useEffect, useState } from 'react'

/*
  Loads the real data files generated by web/scripts/build_data.py
  (champion odds, bracket, groups, fixtures, players, match detail — all from
  the live 2026 World Cup API + our prediction model). Served as static JSON
  from /data/, refreshed on the server every 15 minutes by
  .github/workflows/refresh-data.yml (each refresh commits + triggers a Vercel
  redeploy). `cache: 'no-store'` + a cache-busting query param below make sure
  every page load/refresh fetches the current file over the network instead of
  reusing a stale browser- or CDN-cached copy.
*/

const DataContext = createContext(null)

const FILES = ['predictions', 'groups', 'players', 'fixtures', 'matches']

export function DataProvider({ children }) {
  const [data, setData] = useState(null)
  const [error, setError] = useState(null)

  useEffect(() => {
    let alive = true
    const bust = Date.now()
    Promise.all(FILES.map((f) => fetch(`/data/${f}.json?t=${bust}`, { cache: 'no-store' }).then((r) => {
      if (!r.ok) throw new Error(`${f}.json ${r.status}`)
      return r.json()
    })))
      .then(([predictions, groups, players, fixtures, matches]) => {
        if (alive) setData({ predictions, groups, players, fixtures, matches })
      })
      .catch((e) => alive && setError(e))
    return () => {
      alive = false
    }
  }, [])

  return <DataContext.Provider value={{ data, error }}>{children}</DataContext.Provider>
}

export function useData() {
  const ctx = useContext(DataContext)
  return ctx || { data: null, error: null }
}
